### ISSUE TITLE
Index View 404 Error

### ISSUE THREAD

**Issue by Kamikuz** [CSCI-GA-2820-FA23-003/promotions#73]
**Describe the bug**
In the promotion index view, there show a 404 error

**To Reproduce**
1. Go to '/'
2. Click any buttons
3. See error

**Expected behavior**
I can create, update, delete and list all the promotions

**Observed behavior**
A clear and concise description of what you actually saw.

**Comment by sashadsouza02** [comment]
Closing as this isn't a bug, its a User Story being worked on
